---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get IP address of enp0s8
      ansible.builtin.command: ip addr show enp0s8
      register: network_eth1_output
      changed_when: false

    - name: Get IP address of enp0s9
      ansible.builtin.command: ip addr show enp0s9
      register: network_eth2_output
      changed_when: false

    - name: Verify IP addresses
      ansible.builtin.assert:
        that:
          - "'inet 192.168.56.10/24' in network_eth1_output.stdout"
          - "'inet 192.168.56.30/24' in network_eth2_output.stdout"
        fail_msg: "Static IPs were not applied correctly"

    - name: Read sysctl values
      ansible.builtin.command: "cat /proc/sys/net/ipv4/{{ item }}"
      loop:
        - ip_unprivileged_port_start
        - ip_forward
        - conf/all/src_valid_mark
      register: network_sysctl_results
      changed_when: false

    - name: Verify sysctl values
      ansible.builtin.assert:
        that:
          - network_sysctl_results.results[0].stdout == '80'
          - network_sysctl_results.results[1].stdout == '1'
          - network_sysctl_results.results[2].stdout == '1'
        fail_msg: "Network sysctl settings were not applied correctly"

