---
- name: Get UID of the podman user
  ansible.builtin.command: "id -u {{ item.user }}"
  changed_when: false
  register: podman_network_user_uid
  loop: "{{ podman_network_list }}"

- name: Verify systemd lingering is enabled for the user
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ item.user }}"
  register: podman_network_linger_stat
  loop: "{{ podman_network_list }}"

- name: Assert systemd lingering is enabled
  ansible.builtin.assert:
    that:
      - item.stat.exists
    fail_msg: "Systemd lingering is NOT enabled for {{ item.item.user }}. Please ensure the 'podman' role is applied first."
  loop: "{{ podman_network_linger_stat.results }}"

- name: Ensure podman systemd quadlet directory exists
  ansible.builtin.file:
    path: "/home/{{ item.user }}/.config/containers/systemd"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0700"
  loop: "{{ podman_network_list }}"
  become: true

- name: Template network quadlet files
  ansible.builtin.template:
    src: network.quadlet.j2
    dest: "/home/{{ item.user }}/.config/containers/systemd/{{ item.name }}.network"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0644"
  loop: "{{ podman_network_list }}"
  when: item.state | default('present') == 'present'
  become: true
  notify: Reload user systemd daemon

- name: Remove network quadlet files
  ansible.builtin.file:
    path: "/home/{{ item.user }}/.config/containers/systemd/{{ item.name }}.network"
    state: absent
  loop: "{{ podman_network_list }}"
  when: item.state | default('present') == 'absent'
  become: true
  notify: Reload user systemd daemon

# We must flush handlers here before attempting to start/enable the generated services
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start and enable podman network services
  ansible.builtin.systemd:
    name: "{{ item.item.name }}-network.service"
    state: started
    enabled: true
    scope: user
  loop: "{{ podman_network_user_uid.results }}"
  when: item.item.state | default('present') == 'present'
  become: true
  become_user: "{{ item.item.user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ item.stdout }}"
