---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true


- name: Install Podman and dependencies
  ansible.builtin.apt:
    name:
      - podman
      - acl
    state: "{{ podman_state }}"
  become: true

- name: Enable lingering for the user
  ansible.builtin.command: "loginctl enable-linger {{ podman_user }}"
  args:
    creates: "/var/lib/systemd/linger/{{ podman_user }}"
  become: true

- name: Get UID of the podman user
  ansible.builtin.command: "id -u {{ podman_user }}"
  changed_when: false
  register: user_id_result

- name: Ensure podman socket is enabled (for rootless/api access)
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: true
    scope: user
  become: true
  become_user: "{{ podman_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user_id_result.stdout }}"