---
- name: Set unprivileged port start
  ansible.builtin.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "{{ network_unprivileged_port_start | string }}"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/99-network-custom.conf
  become: true
  when: network_unprivileged_port_start is defined

- name: Deploy Netplan configuration
  ansible.builtin.template:
    src: netplan.yaml.j2
    dest: /etc/netplan/00-ansible-network.yaml
    mode: '0600'
  become: true
  notify: Apply Netplan
