---
- name: Harden Ubuntu 24.04 Servers
  hosts: all
  become: yes
  roles:
    - ubuntu_hardening
  vars:
    ubuntu_hardening:
      ssh:
        port: 2222
        allow_groups: ["sudo", "devs"]
      system:
        unattended_upgrades:
          mail: "admin@example.com"
      account:
        password_aging:
          enabled: true
          max_days: 180