---
- name: Converge server
  hosts: server
  vars:
    wireguard_server_private_ip: "192.168.56.10"
  tasks:
    - name: "Include network role"
      ansible.builtin.include_role:
        name: "network"
      vars:
        network_sysctl_settings:
          net.ipv4.ip_forward: 1
          net.ipv4.conf.all.src_valid_mark: 1
        network_interfaces:
          - name: enp0s8
            addresses:
              - "{{ wireguard_server_private_ip }}/24"

    - name: "Include podman role"
      ansible.builtin.include_role:
        name: "podman"

    - name: "Include podman_user role"
      ansible.builtin.include_role:
        name: "podman_user"
      vars:
        podman_user_list: ["wireguard"]

    - name: "Include wireguard role"
      ansible.builtin.include_role:
        name: "wireguard"
      vars:
        wireguard_server_url: "{{ wireguard_server_private_ip }}"
        wireguard_peers: 1
        wireguard_allowed_ips: "10.13.13.0/24"

- name: Converge client
  hosts: client
  tasks:
    - name: "Include network role"
      ansible.builtin.include_role:
        name: "network"
      vars:
        network_sysctl_settings: {}
        network_interfaces:
          - name: enp0s8
            addresses:
              - "192.168.56.11/24"

    - name: Install WireGuard client tooling
      ansible.builtin.apt:
        name: wireguard-tools
        state: present
        update_cache: true
      become: true
